### ISSUE TITLE
Update prerequisites version please

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#118]
Hi @smicyk How are you. Happy 2024!

I'm setting up my [groovy-jmeter](https://github.com/smicyk/groovy-jmeter) again, is it possible to bring the prerequisites versions to the following pls?

- groovy @4.0.17
- gradle @8.5

These are the versions my [MacPorts](https://www.macports.org/) reports currently, which can save me lots of struggle going back to old versions. 

UPDATE:

Hmm... I cannot remember why the versions have to be match, but I do remember there has been a time when things were not working when the versions were not matched. Ah, found it https://github.com/smicyk/groovy-jmeter/issues/52#issuecomment-1022662138.

Thanks

**Comment by AntonioSun** [comment]
> but I do remember there has been a time when things were not working when the versions were not matched.

yep, duplicated:

```sh
$ groovy example.groovy --help
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-xml is loaded in version 4.0.17 and you are trying to load version 3.0.17

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-xml is loaded in version 4.0.17 and you are trying to load version 3.0.17
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:524)
. . .
```

**Comment by smicyk** [comment]
Hi @AntonioSun, Quite fine thanks.

Regarding your request the general rule is that I stick to versions which are used by jmeter. So currently it is groovy 3.x and I'm not sure if it is possible to update it right now without breaking some stuff on jmeter side. I will have a look and see if there are any problems.

I'm pretty sure that you can use gradle 8.5 in your project since the gradle requirement is only valid when you build from source.

The good thing is that there is new version of jmeter 5.6.3 which update gradle builds to 8.5 so I will update groovy-jmeter soon to use that version. Also they have plans to upgrade groovy to 4.x in next major release hopefully it will be soon.

If possible you can try to run in docker either as gradle project or just normal groovy script. Then you don't have to worry about versions. In the examples folder you can find some examples :).

Hope that helps.

**Comment by AntonioSun** [comment]
Oh, sure, I fully believe in your choice, which is very reasonable and convincing. will do. thx

BTW, I'm closing this for now, but please drop here a line when you've done the update. thx
