### ISSUE TITLE
View Results Tree defaults

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#72]
Following up on #59

As per the guideline of

> All keywords in the DSL has predefined default values for its properties. For example, each keyword has name property with a default value defined. If there is no name property given for the keyword, the script will use the default value. 

I'm proposing the `view()` to have the following default values:

- `name`: 'View Result Tree' or even blank if possible, 
- `file`: not required as this is view only by default
- `enabled`: true`

These are the _**defaults**_ when you add a View Results Tree component to JMeter GUI.

I.e., this need to be fixe:

`Caught: net.simonix.dsl.jmeter.model.ValidationException: The keyword 'view' is missing required properties. Did you forget to add any of the required properties [file]?`

Comments?

**Comment by smicyk** [comment]
I added fix for the file property and name, so:
- the __name__ has 'View Result Tree' value by default (similar to others elements)
- the __file__ is not required property
- the __enable__ stays false by default, this is mainly because the scripts are run on command line without gui components, the jmeter recommendation regarding listeners is to disable them to not waste resources

You can still use command line variable to dynamically set the enabled property depending if you want to run the script or just generate the jmx file.

**Comment by AntonioSun** [comment]
Hmm... how do I upgrade? 

Would everything get upgraded by itself next time I run it?

**Comment by smicyk** [comment]
If you want latest changes you need to build from source. When you clone use build_local or build_docker script depending how you use the script. Otherwise you need to wait for next version release.

**Comment by AntonioSun** [comment]
Gotya. thx! I'll wait.
